"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import { ArrowRight, CircleNotch, FileText, Info, UploadSimple } from "@phosphor-icons/react";
import { AnalysisPhase, getAnalysisStages } from "@/lib/analysis-phase";
import { parseSseBlocks } from "@/lib/sse";

type Lane = { status: "available" | "unavailable"; score?: number; band?: "low" | "elevated" | "high"; decision?: string; reason?: string; };
type Analysis = { word_count: number; truncated: boolean; models: { raw_ai: Lane; humanized_ai: Lane }; };
const MAX_CHARACTERS = 40_000;
const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
function words(text: string) { return (text.match(/\b[\w'-]+\b/g) ?? []).length; }

function Unavailable({ name, reason }: { name: string; reason?: string }) {
  return <section className="lane unavailable"><div className="lane-top"><div><span className="eyebrow">Model status</span><h3>{name}</h3></div><span className="badge">unavailable</span></div><p className="lane-summary">This lane could not complete live inference. No score has been shown.</p><p className="lane-detail mono">{reason ?? "MODEL LOAD UNAVAILABLE"}</p></section>;
}
function RawLane({ lane }: { lane: Lane }) {
  if (lane.status === "unavailable") return <Unavailable name="Raw AI detector" reason={lane.reason} />;
  const detected = lane.decision === "ai_characteristics_detected";
  return <section className="lane"><div className="lane-top"><div><span className="eyebrow">Lane 01 / ONNX</span><h3>Raw AI detector</h3></div><span className={`badge ${detected ? "elevated" : ""}`}>{detected ? "possible AI signal" : "no strong signal"}</span></div><p className="lane-summary">{detected ? "Possible AI-like patterns detected. Treat this as a prompt for review, not proof of AI authorship." : "No strong AI-like signal was detected by this experimental model. This does not rule out AI involvement."}</p><p className="lane-detail mono">EXPERIMENTAL / UNCALIBRATED SCORE · {lane.score?.toFixed(4)}</p></section>;
}
function HumanizerLane({ lane }: { lane: Lane }) {
  if (lane.status === "unavailable") return <Unavailable name="Humanized-AI detector" reason={lane.reason} />;
  const label = lane.band === "high" ? "possible humanized AI" : lane.band === "elevated" ? "possible humanized AI" : "no strong signal";
  const copy = lane.band === "high" ? "Possible humanized-AI signal detected at the stricter operating point. This remains a model signal, not proof of authorship." : lane.band === "elevated" ? "Possible humanized-AI signal detected. This crossed the deployed review threshold, but it is not proof of authorship." : "No strong humanized-AI signal was detected. A low result does not rule out AI involvement, especially after substantial human editing.";
  return <section className="lane"><div className="lane-top"><div><span className="eyebrow">Lane 02 / V4.8</span><h3>Humanized-AI detector</h3></div><span className={`badge ${lane.band}`}>{label}</span></div><p className="lane-summary">{copy}</p><p className="lane-detail mono">RAW MODEL SCORE · {lane.score?.toFixed(4)} · NOT A PROBABILITY</p></section>;
}

function AnalysisProgress({ phase }: { phase: AnalysisPhase }) {
  const stages = getAnalysisStages(phase);
  return <div className={`analysis-progress ${phase === "idle" ? "is-idle" : ""}`} aria-live="polite">
    {stages.map((stage, index) => <div className={`progress-stage ${stage.state}`} key={stage.label}>
      <span className="progress-dot">{stage.state === "complete" ? "✓" : index + 1}</span>
      <div><strong>{stage.label}</strong><small>{stage.state === "active" ? phase === "checking" ? "Connecting to live inference" : phase === "complete" ? "Analysis ready" : "Inference in progress" : stage.state === "complete" ? "Complete" : "Waiting"}</small></div>
    </div>)}
  </div>;
}

export function AnalysisStation() {
  const [text, setText] = useState(""); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [pending, setPending] = useState(false); const [phase, setPhase] = useState<AnalysisPhase>("idle"); const [error, setError] = useState<string | null>(null); const fileInput = useRef<HTMLInputElement>(null); const wordCount = useMemo(() => words(text), [text]);
  async function analyze() { if (!text.trim() || pending) return; const startedAt = performance.now(); const visualDuration = 2000 + Math.random() * 3000; const waitFor = async (targetElapsed: number) => { const remaining = targetElapsed - (performance.now() - startedAt); if (remaining > 0) await new Promise((resolve) => setTimeout(resolve, remaining)); }; setPending(true); setPhase("checking"); setError(null); setAnalysis(null); try { const response = await fetch(`${API_BASE_URL}/v1/analyze/stream`, { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify({ text }) }); if (!response.ok || !response.body) throw new Error("The live inference service is unavailable."); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value ?? new Uint8Array(), { stream: !done }); const blocks = buffer.split("\n\n"); buffer = done ? "" : blocks.pop() ?? ""; for (const event of parseSseBlocks(blocks.join("\n\n"))) { if (event.event === "raw_model") { await waitFor(visualDuration / 3); setPhase("raw"); } if (event.event === "humanizer") { await waitFor((visualDuration / 3) * 2); setPhase("humanizer"); } if (event.event === "complete") { await waitFor(visualDuration); setAnalysis(event.data as unknown as Analysis); setPhase("complete"); } } if (done) break; } } catch (failure) { setError(failure instanceof Error ? failure.message : "The live inference service is unavailable."); setPhase("idle"); } finally { setPending(false); } }
  async function loadFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > MAX_CHARACTERS) { setError("Please choose a .txt file smaller than 40,000 characters."); return; } const contents = await file.text(); setText(contents); setAnalysis(null); setError(null); setPhase("idle"); }
  return <>
    <section className="hero"><div className="shell hero-grid"><div><span className="eyebrow">Independent inference / two model lanes</span><h1>Read the signal.<br /><em>Keep the doubt.</em></h1><p className="hero-copy">Analyze a document with the deployed raw-AI and humanized-AI models. The system returns model signals, not proof of authorship.</p></div><div className="fact-grid"><div className="fact"><strong>Two live lanes</strong><span>Independent ONNX and PyTorch model outputs.</span></div><div className="fact"><strong>Private by design</strong><span>Submitted text is not stored in the browser or API logs.</span></div><div className="fact"><strong>5% FPR default</strong><span>Humanizer lane uses a frozen operating threshold.</span></div><div className="fact"><strong>Honest failure states</strong><span>A missing model reports unavailable, never a made-up score.</span></div></div></div></section>
    <section className="station shell" id="detector"><div className="station-head"><div><span className="eyebrow">Analysis station / 01</span><h2>Submit a document for live analysis</h2></div><p className="station-meta mono">LIMIT 40,000 CHARACTERS<br />TEXT IS NOT SAVED</p></div><div className="station-grid"><section className="panel editor-panel"><div className="panel-bar"><span className="mono">INPUT / PLAIN TEXT</span><label className="upload"><UploadSimple size={15} /> import .txt<input ref={fileInput} type="file" accept="text/plain,.txt" onChange={loadFile} /></label></div><textarea className="editor" value={text} maxLength={MAX_CHARACTERS} onChange={(event) => { setText(event.target.value); setAnalysis(null); setPhase("idle"); }} placeholder="Paste a document here. The two deployed models will evaluate it independently." aria-label="Text to analyze" /><p className="sample-note">Long documents are sampled from the beginning, middle, and end — not read in full.</p><div className="editor-foot"><span className="mono" style={{ color:"var(--faint)",fontSize:10 }}>{wordCount.toLocaleString()} WORDS · {text.length.toLocaleString()}/{MAX_CHARACTERS.toLocaleString()} CHARS</span><button className="analyze" onClick={analyze} disabled={!text.trim() || pending}>{pending ? <CircleNotch className="spin" size={17} /> : <ArrowRight size={17} weight="bold" />}{pending ? "Analyzing live models" : "Analyze text"}</button></div></section><aside className="results" aria-live="polite">{analysis ? <><div className="result-intro"><span className="eyebrow">Live result / {analysis.word_count} words</span><h3>Independent signals returned.</h3><p>{analysis.truncated ? "The input was truncated to the supported model limit." : "Both lanes were asked to evaluate the submitted text."}</p></div><RawLane lane={analysis.models.raw_ai} /><HumanizerLane lane={analysis.models.humanized_ai} /></> : <div className="empty"><div><FileText size={30} weight="thin" /><p>{pending ? "Checking the service and running live inference…" : "Your live results will appear here. The models run independently; an unavailable lane will be shown honestly."}</p></div></div>}{error && <div className="error">{error}</div>}</aside></div><AnalysisProgress phase={phase} /><div className="disclaimer"><Info size={18} color="var(--signal)" weight="fill" /><div><strong>This analysis is probabilistic and is not proof of authorship.</strong><br />A low result does not rule out AI involvement, particularly after substantial human editing.</div></div><details className="details"><summary>Model limits and interpretation</summary><p>The humanized-AI detector is more effective on LLM-edited or generic AI-style writing than on text carefully edited by a human expert — for that category, current performance is close to chance. The raw AI detector&apos;s score is experimental and uncalibrated. Neither score is a universal probability of AI authorship.</p></details></section>
  </>;
}
